version: '2'
services:
  shell:
    image: transnano/shell-exit-status-exporter:v0.0.6
    container_name: shell
    ports:
     - 9062:9062
    volumes:
     - ./config.yml:/etc/shell-exit-status-exporter/config.yml:ro
  prometheus:
    image: prom/prometheus:v2.25.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:6.7.5
    container_name: grafana
    ports:
      - 3000:3000
  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: node
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs

