global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'my-monitor'

rule_files:
#   - "/var/app/prometheus/alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node:9100'
  - job_name: 'shell-exit-status-exporter'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      pattern:
        - '.*'
    static_configs:
      - targets:
        - 'shell:9121'
